#!/usr/bin/python

# VT documentation: https://www.virustotal.com/en/documentation/public-api/

import argparse
import hashlib
import http.client
import json
import os
import time

# https://www.virustotal.com/gui/user/<login>/apikey
vt_api_key = ''


def sha256_hash(file):
    file_hash_sha256 = hashlib.sha256()
    file_hash_md5 = hashlib.md5()
    block_size = 65536
    with open(file, 'rb') as f:
        fb = f.read(block_size)
        while len(fb) > 0:
            file_hash_sha256.update(fb)
            file_hash_md5.update(fb)
            fb = f.read(block_size)
    return file_hash_sha256.hexdigest()


def vt_check(hash):
    positives = '-'
    total = '-'

    conn = http.client.HTTPSConnection("www.virustotal.com")
    conn.request('GET', f'/vtapi/v2/file/report?apikey={vt_api_key}&resource={hash}')
    res = conn.getresponse()
    if res.status == 200:
        data = res.read()
        if data:
            data_decoded = json.loads(data)
            if data_decoded['response_code'] == 1:
                status = f'https://www.virustotal.com/gui/search/{hash}'
                positives = data_decoded['positives']
                total = data_decoded['total']
            else:
                status = 'VT - file not found'
        else:
            status = 'VT - unable to get page content'
    else:
        status = 'VT - returned code != 200'

    conn.close()
    return status, positives, total


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('files', metavar='file', type=str, nargs='+', help='File(s) to check')
    args = parser.parse_args()
    files = args.files

    for file in files:
        if not os.path.isfile(file):
            continue

        file_hash = sha256_hash(file)
        vt_url, positives, total = vt_check(file_hash)

        print(f'{file}\t{file_hash}\t({positives}/{total})\t{vt_url}')

        if len(files) > 4:
            time.sleep(16)


if __name__ == '__main__':
    main()
